### ISSUE TITLE
Support client-side email authentication with Go

### ISSUE THREAD

**Issue by gabesullice** [magiclabs/magic-admin-go#4]
First, I love Magic! Super cool.

I'm writing a tool for my users to interact with my application via a command line interface (written in Go). Currently, I can support this by allowing them to can log into my web app using an email sent by magic.link after which they can generate a machine token to use in their terminal. This is not ideal because:

1. I have to support two authentication methods
2. They need to store a secret

IMO, their experience would be better if they passed their email to my CLI utility and then clicked a magic link in their email inbox, just as they would when logging into my web application. Their experience would look something like this:

```
$ mycli --email=name@example.com --other-flags
please check your inbox and click the magic link in your inbox. time remaining: 4m13s
```

Note that I would not expect this library to be responsible for printing that message to STDERR (I'm happy to handle that myself). Therefore, my Go code could look something like this:

```go
m := client.New("my_publishable_key", magic.NewPublicClient())
ctx, cancel := context.WithTimeout(context.Background(), time.Minute * 5)
defer cancel()
did, err := m.User.loginWithMagicLink(ctx, email)
```

In this example, `m.User.loginWithMagicLink` would block until the user clicked the magic link in their inbox.

Thanks for considering this!

P.S. Please let me know if I should move this issue to a different repository or ticketing system.

**Comment by seemcat** [comment]
Hi @gabesullice! Ty for your patience on this. Surfaced this to the team today and learned that it's infeasible to use Magic on the CLI. We rely on web browsers for our non-custodial key architecture. One workaround is that you could open a browser tab from the CLI and allow a user to sign in through the browser. (_Btw, I sent this same msg to you on Discord. Pls feel free to respond either here or there._)

**Comment by seemcat** [comment]
Hi @gabesullice! 

Ty for your patience on this. Surfaced this to the team today and learned that it's infeasible to use Magic on the CLI. We rely on web browsers for our non-custodial key architecture. One workaround is that you could open a browser tab from the CLI and allow a user to sign in through the browser. 

For this reason, I'll be closing the ticket.

(_Btw, I sent this same msg to you on Discord. Pls feel free to respond there._)
