### ISSUE TITLE
Depedency on old version of go-ethereum exposing security vulnerabilities.

### ISSUE THREAD

**Issue by KOGI** [magiclabs/magic-admin-go#7]
See: https://deps.dev/go/github.com%2Fmagiclabs%2Fmagic-admin-go/v0.1.0
which is corroborated by: https://deps.dev/go/github.com%2Fethereum%2Fgo-ethereum/v1.9.24

The latest version of go-ethereum is v1.10.20, which fixes nearly all of these issues.
See: https://deps.dev/go/github.com%2Fethereum%2Fgo-ethereum/v1.10.20

**Comment by justinnout** [comment]
Bumped up the version in https://github.com/magiclabs/magic-admin-go/pull/10
